# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amazon/mt8163-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter biscuit checkers cronos crown douglas giza karnak mustang rook,$(TARGET_DEVICE)),)

endif
